### ISSUE TITLE
Where do IRQs 2-7 connect to the CPU?

### ISSUE THREAD

**Issue by tedchoward** [Turaco-System/Turaco-Hardware#1]
I see you have a Bus Alias named `Interrupts` that includes `~{IRQ}[0..7]`. I see on the schamatic where IRQ0 and IRQ1 connect to the CPU.

<img width="273" alt="Screenshot 2023-08-10 at 9 30 07 AM" src="https://github.com/Turaco-System/Turaco-Hardware/assets/470549/3ae7314e-3da8-4ded-ad26-2ecbbf5b876c">

What I don't see are where the other IRQ lines connect to the CPU.

Or are there only 2 IRQ lines, and the alias is wrong?

Or am I missing something obvious?

**Comment by KyleCardoza** [comment]
IRQs 2-7 have been subsumed into the GPIO port -- as each of the 16 pins on the GPIO port can be an IRQ source in its own right. The bus alias is a leftover from an earlier iteration. I'll go ahead and fix that now.
